import { gunzipSync } from 'node:zlib';

const MASTER_URL='https://www.cashmarket.deutsche-boerse.com/resource/blob/1528/a31c10e3183f4c5dd721f9c7f9eaaaea/data/t7-xetr-allTradableInstruments.csv';
const FEEDS=[
  {key:'xetraPretrade',prefix:'DETR-pretrade',venue:'Xetra',kind:'pre',mic:['XETR','XETA','XETB','XETS'],window:45},
  {key:'xetraPosttrade',prefix:'DETR-posttrade',venue:'Xetra',kind:'post',mic:['XETR','XETA','XETB','XETS'],window:150},
  {key:'tradegate',prefix:'DGAT-pretrade',venue:'Tradegate',kind:'pre',mic:['XGAT','DGAT'],window:45},
  {key:'frankfurt',prefix:'DFRA-pretrade',venue:'Frankfurt',kind:'pre',mic:['XFRA','FRAA','FRAB'],window:45},
];
const MASTER_CACHE=globalThis.__TH66_MASTER_550__||(globalThis.__TH66_MASTER_550__={at:0,items:[]});
function pad(n){return String(n).padStart(2,'0')}
function csv(line,d=';'){const o=[];let c='',q=false;for(let i=0;i<line.length;i++){const x=line[i];if(x==='"'){if(q&&line[i+1]==='"'){c+='"';i++}else q=!q}else if(x===d&&!q){o.push(c);c=''}else c+=x}o.push(c);return o}
function key(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function col(h,names){const a=h.map(key);for(const n of names){const k=key(n),i=a.findIndex(x=>x===k||x.includes(k));if(i>=0)return i}return -1}
async function master(){if(MASTER_CACHE.items.length&&Date.now()-MASTER_CACHE.at<12*3600000)return MASTER_CACHE.items;const r=await fetch(MASTER_URL,{cache:'no-store',headers:{'User-Agent':'Depot-Cockpit-TH66/5.5.1'}});if(!r.ok)throw new Error('Instrument-Master HTTP '+r.status);const t=await r.text(),ls=t.split(/\r?\n/).filter(Boolean);const d=ls[0].includes(';')?';':',';const h=csv(ls[0],d);const ni=col(h,['instrumentname','name','shortname']),ii=col(h,['isin']),wi=col(h,['wkn']),mi=col(h,['mnemonic','ticker','symbol']),idi=col(h,['instrumentid','securityid']),ci=col(h,['currency','tradingcurrency']);const items=[];for(const l of ls.slice(1)){const c=csv(l,d),isin=String(c[ii]||'').trim().toUpperCase();if(!/^[A-Z]{2}[A-Z0-9]{9}[0-9]$/.test(isin))continue;items.push({name:String(c[ni]||isin).trim(),isin,wkn:wi>=0?String(c[wi]||'').trim().toUpperCase():'',mnemonic:mi>=0?String(c[mi]||'').trim().toUpperCase():'',instrumentId:idi>=0?String(c[idi]||'').trim().toUpperCase():'',currency:ci>=0?String(c[ci]||'EUR').trim().toUpperCase():'EUR'})}MASTER_CACHE.items=items;MASTER_CACHE.at=Date.now();return items}
function enrichPositions(positions,items){return positions.map(p=>{const hit=items.find(x=>x.isin===String(p.isin||'').toUpperCase())||items.find(x=>x.wkn&&x.wkn===String(p.wkn||'').toUpperCase())||items.find(x=>x.mnemonic&&x.mnemonic===String(p.mnemonic||'').toUpperCase());return {...p,master:hit||null,instrumentId:hit?.instrumentId||'',masterMnemonic:hit?.mnemonic||'',currency:hit?.currency||p.currency||'EUR'}})}
function prevWeekday(d){const x=new Date(d);do{x.setUTCDate(x.getUTCDate()-1)}while([0,6].includes(x.getUTCDay()));return x}
function sessionAnchor(now=new Date()){let d=new Date(now.getTime()-16*60000);if([0,6].includes(d.getUTCDay()))d=prevWeekday(d);let open=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),7,0)),close=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),17,30));if(d<open){d=prevWeekday(d);close=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),17,30));return close}return d>close?close:d}
function minuteNames(prefix,count){const end=sessionAnchor(),out=[];for(let i=0;i<count;i++){const d=new Date(end.getTime()-i*60000);out.push(`${prefix}-${d.getUTCFullYear()}-${pad(d.getUTCMonth()+1)}-${pad(d.getUTCDate())}T${pad(d.getUTCHours())}_${pad(d.getUTCMinutes())}.json.gz`)}return out}
async function fetchGz(name){const c=new AbortController(),t=setTimeout(()=>c.abort(),3500);try{const r=await fetch('https://mfs.deutsche-boerse.com/api/download/'+name,{signal:c.signal,cache:'no-store',headers:{Accept:'application/gzip, application/octet-stream, */*','User-Agent':'Depot-Cockpit-TH66/5.5.1'}});if(!r.ok)return null;const b=Buffer.from(await r.arrayBuffer());return b.length?b:null}catch{return null}finally{clearTimeout(t)}}
function docs(buf){try{const s=gunzipSync(buf).toString('utf8').replace(/^\uFEFF/,'').trim();if(!s)return[];try{const x=JSON.parse(s);return Array.isArray(x)?x:[x]}catch{return s.split(/\r?\n/).map(x=>{try{return JSON.parse(x)}catch{return null}}).filter(Boolean)}}catch{return[]}}
function leaves(v,path='',out=[]){if(Array.isArray(v)){v.forEach((x,i)=>leaves(x,`${path}[${i}]`,out));return out}if(v&&typeof v==='object'){for(const[k,x]of Object.entries(v))leaves(x,path?`${path}.${k}`:k,out);return out}out.push({path,key:key(path.split('.').at(-1)||''),value:v});return out}
function n(v){if(typeof v==='number'&&Number.isFinite(v))return v;if(typeof v!=='string')return null;const s=v.trim().replace(/\s/g,'').replace(',','.');if(!/^[-+]?\d+(\.\d+)?$/.test(s))return null;const x=Number(s);return Number.isFinite(x)?x:null}
function tokenSet(p){return new Set([p.isin,p.wkn,p.mnemonic,p.instrumentId,p.masterMnemonic].map(x=>String(x||'').trim().toUpperCase()).filter(x=>x.length>=3))}
function match(ls,p){const ts=tokenSet(p);for(const l of ls){const v=String(l.value??'').trim().toUpperCase();for(const t of ts)if(v===t||(t.length>=6&&v.includes(t)))return true}return false}
function findByKeys(ls,words){for(const l of ls){if(words.some(w=>l.key===w||l.key.includes(w))){const x=n(l.value);if(x!=null&&x>0)return x}}return null}
function findCurrency(ls,fallback='EUR'){for(const l of ls){const v=String(l.value||'').toUpperCase();if((l.key.includes('currency')||l.key.includes('ccy'))&&/^[A-Z]{3}$/.test(v))return v}return fallback}
function findTime(ls){for(const l of ls){if(typeof l.value==='string'&&/20\d\d[-T]/.test(l.value)&&Number.isFinite(Date.parse(l.value)))return new Date(l.value).toISOString()}return null}
function eventObjects(v,out=[]){if(Array.isArray(v)){for(const x of v)eventObjects(x,out);return out}if(v&&typeof v==='object'){const ls=leaves(v);const hasIdentifier=ls.some(l=>/isin|instrument|security|mnemonic|wkn/i.test(l.path));const hasPrice=ls.some(l=>/price|bid|ask|pric|px/i.test(l.path)&&n(l.value)!=null);if(hasIdentifier&&hasPrice){out.push(v);return out}for(const x of Object.values(v))if(x&&typeof x==='object')eventObjects(x,out)}return out}
function quoteFromEvent(ev,p,feed){const ls=leaves(ev);if(!match(ls,p))return null;const bid=findByKeys(ls,['bid','bidprice','bestbid','bidpx']);const ask=findByKeys(ls,['ask','askprice','bestask','offer','offerprice','bestoffer','askpx']);const last=findByKeys(ls,['tradeprice','transactionprice','lastprice','executedprice','tradedprice','price','pric']);let price=null,method='';if(feed.kind==='pre'&&bid&&ask){price=(bid+ask)/2;method='mid'}else if(feed.kind==='pre'&&(bid||ask)){price=bid||ask;method=bid?'bid':'ask'}else if(last){price=last;method='last'}else if(bid&&ask){price=(bid+ask)/2;method='mid'};if(!(price>0))return null;return {price,bid,ask,last,method,time:findTime(ls),currency:findCurrency(ls,p.currency||'EUR')}}
async function scanFeed(feed,positions,missingOnly=true){const hits=new Map(),names=minuteNames(feed.prefix,feed.window);let attempted=0,parsed=0;const B=12;for(let i=0;i<names.length;i+=B){const batch=names.slice(i,i+B),got=await Promise.all(batch.map(async name=>({name,b:await fetchGz(name)})));attempted+=got.length;for(const f of got){if(!f.b)continue;const ds=docs(f.b);if(!ds.length)continue;parsed++;for(const d of ds){for(const ev of eventObjects(d)){for(const p of positions){if(hits.has(p.id))continue;const q=quoteFromEvent(ev,p,feed);if(q){hits.set(p.id,{...q,file:f.name,venue:feed.venue,feed:feed.key})}}}}}if(hits.size===positions.length)break}return {hits,attempted,parsed}}
export async function buildMarketSnapshot(positions){const mi=await master();const enriched=enrichPositions(positions,mi),resolved=enriched.filter(p=>p.master).length;const final=new Map(),coverage={instrumentMasterResolved:resolved,xetraPretrade:0,xetraPosttrade:0,tradegate:0,frankfurt:0},feedDiagnostics=[];for(const feed of FEEDS){const remaining=enriched.filter(p=>!final.has(p.id));if(!remaining.length)break;const r=await scanFeed(feed,remaining);coverage[feed.key]=r.hits.size;for(const [id,h] of r.hits)final.set(id,h);feedDiagnostics.push({feed:feed.key,attempted:r.attempted,parsed:r.parsed,found:r.hits.size})}
 const results=enriched.flatMap(p=>{const h=final.get(p.id);if(!h)return[];return[{id:p.id,ok:true,latest:{price:h.price,date:(h.time||new Date().toISOString()).slice(0,10)},source:`Deutsche Börse Delayed · ${h.venue} ${h.feed.includes('pre')?'Pre-Trade':'Post-Trade'}`,usedVenue:h.venue,currency:h.currency,quote:{bid:h.bid,ask:h.ask,last:h.last,method:h.method},sourceMeta:{provider:h.feed,delayedMinutes:15,asOf:h.time,officialFile:h.file,instrumentId:p.instrumentId,masterMnemonic:p.masterMnemonic,matchedBy:'Instrument-Master + ISIN/WKN/Mnemonic/Instrument-ID'}}]});
 return {ok:true,generationId:`mdc-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,provider:'Depot-Cockpit Market Data Core 5.5.1',generatedAt:new Date().toISOString(),delayedMinutes:15,coverage,results,diagnostics:{feeds:feedDiagnostics,requested:positions.length,found:results.length,missing:enriched.filter(p=>!final.has(p.id)).map(p=>({id:p.id,name:p.name,isin:p.isin,masterResolved:!!p.master,instrumentId:p.instrumentId,masterMnemonic:p.masterMnemonic}))}}}
export const __test={enrichPositions,sessionAnchor,minuteNames,leaves,match,quoteFromEvent,eventObjects};
